### ISSUE TITLE
How to remove item from array

### ISSUE THREAD

**Issue by GreyCode3** [2bonahill/nanodb#1]
Hi, I only find push method to push into an array, if there is any method to remove item from array directly? or I need get array first and remove whole array by key, then update one of item in array and insert again?

**Comment by 2bonahill** [comment]
Hi. Thanks for your message. Yes, at the moment there is no direct way of removing an item from an array. Yes, you can use the workaround as you describe.

But I think your request is very valid. I am happy to implement a remove method for arrays.

Maybe something similar to the remove method of Vec:

pub fn [remove](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.remove)(&mut self, index: [usize](https://doc.rust-lang.org/std/primitive.usize.html)) -> T

Would that be something you are looking for?

**Comment by 2bonahill** [comment]
Hi again. 

There is a new method on tree and on the write guarded tree:

pub fn remove_at(&mut self, index: usize) -> Result<&mut Self, NanoDBError>

BR
